#!/bin/sh
#
# Bootstrap script for setting up a new OSX machine
#
# This should be idempotent so it can be run multiple times.
#

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

# Homebrew bootstrap
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  echo "Doing OSX install of yadm"

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  else
    echo "Homebrew already installed. Getting updates..."
    /opt/homebrew/bin/brew update
    /opt/homebrew/bin/brew doctor
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle install --global --file ~/.config/Brewfile
  fi
fi

hash yadm 2>/dev/null || (echo "yadm install failed" && exit 1)

# always checkout and update
yadm checkout -f && \
  yadm pull --rebase && \
  yadm submodule && \
  yadm submodule update --init --recursive && \
  yadm alt && \
  yadm perms

# To install useful key bindings and fuzzy completion:
$(brew --prefix)/opt/fzf/install

echo "Bootstrapping complete"
