# Brewfile for Luis Medina's setup

# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# CLI tools
brew "awk"           # Text processing
brew "curl"
brew "wget"
brew "git"
brew "zsh"
brew "fd"           # Alternative to find
brew "fzf"
brew "bat"          # Cat with syntax highlighting
brew "zplug"        # Zsh plugin manager
brew "neovim"
brew "ripgrep"      # Search tool
brew "tree"
brew "jq"
brew "yadm"         # For dotfile management
brew "maven"        # Java build tool

brew "zsh-syntax-highlighting" 
brew "zsh-completions"          
brew "zsh-autosuggestions"      


# Development tools
brew "pyenv"        # Python version management
brew "jenv"         # Java version management

# Applications
cask "visual-studio-code"
cask "rancher"      # Kubernetes management

# Optional - Uncomment if needed
cask "iterm2"
# cask "docker"
# cask "rectangle"    # Window management
